### ISSUE TITLE
setTransformer() doesn't work now

### ISSUE THREAD

**Issue by ted9219** [OHDSI/DeepPatientLevelPrediction#35]
Hi, 
setTransformer() doesn't work now, it seems due to the default values of parameters. They have just one set of parameters, so random param sampling cannot work.

![image](https://user-images.githubusercontent.com/42205861/188878239-4bc664d6-3d3f-406a-86ca-f4cc84e07643.png)
![image](https://user-images.githubusercontent.com/42205861/188877638-00cd703d-78a1-4206-8513-682888677e30.png)

**Comment by egillax** [comment]
Thanks. This was because randomSamples had a default value of 100 but as you noticed there is only one set of parameters defined. I changed the default value of randomSamples=1 for the transformer and added a check with an error message if the amount of randomSamples is higher than the possible configurations of hyperparameters.

**Comment by egillax** [comment]
This is fixed in the first release.
